[commit]

pattern = "^[A-Z]+-\\d+\\s\\|\\s[A-Z]+\\s:\\s.+$"
strict = true


[ticket]

pattern = "^[A-Z]+-\\d+$"
uppercase = true


[types]

allowed = [
  "FEAT",
  "INIT",
  "DOCS",
  "TEST",
]


[severity]

invalid_format = "error"
unknown_type = "error"
missing_ticket = "error"
